### ISSUE TITLE
Can't parse 'dsize'. Sequence item with index 1 has a wrong type

### ISSUE THREAD

**Issue by Publiq2** [harisreedhar/Swap-Mukham#1]
Hi, I'm getting this error if I change any Detection Settings value. (Detection Size or Detection Threshold). Even setting them back to the default values doesn't work and a full restart is needed.

Thanks in advance

**Comment by harisreedhar** [comment]
Thanks for the report. Fixed 3ae55ae993fe0e6e848886688e8943dc403da7c5
