### ISSUE TITLE
link gdrive in collab

### ISSUE THREAD

**Issue by mukeshsnp12** [harisreedhar/Swap-Mukham#11]
Link gdrive in collab, As it is not asking permission, it is not saving result.mp4 in gdrive.

**Comment by harisreedhar** [comment]
Good suggestion will add that . 
For now you can get saved result on ``/content/Swap-Mukham/``

**Comment by mukeshsnp12** [comment]
Still, it is not adding folder swap-mukham in my drive. 
Still didn't ask for permission. As you created in your google notebook, it need not permission and it is creating folder. But for others it's need permission to use their google drive. 
I guess you need to mount gdrive in code
drive.mount('/content/')

**Comment by mukeshsnp12** [comment]
from google.colab import auth
auth.authenticate_user()

**Comment by harisreedhar** [comment]
create a cell before **Run App** like this:
````
from google.colab import auth, drive
auth.authenticate_user()
drive.mount('/content/drive')
````
then put your desired drive ouput path in gui output settings.
