### ISSUE TITLE
Slow without gpu & trim takes too long

### ISSUE THREAD

**Issue by fuzzyfazzy** [harisreedhar/Swap-Mukham#2]
As per title, extremely slow processing when using cpu. Trim either errors out or takes too long to perform.

**Comment by harisreedhar** [comment]
Adding gpu support is planned. Can you describe the error occurred while trimming?

**Comment by harisreedhar** [comment]
- Added support for GPU (Nvidia cuda only) # still need lot of work 
- Use ``moviepy`` for trimming & added the start-stop frame sliders
- specific face support added
