### ISSUE TITLE
Not swapping faces looking upside

### ISSUE THREAD

**Issue by mukeshsnp12** [harisreedhar/Swap-Mukham#24]
![frame_0](https://github.com/harisreedhar/Swap-Mukham/assets/131114036/f2b9e430-af0d-439c-bddf-c729499bae41)
![frame_64](https://github.com/harisreedhar/Swap-Mukham/assets/131114036/99c68ec4-f4ef-4395-bc3e-488ba7ef3eb1)
![frame_103](https://github.com/harisreedhar/Swap-Mukham/assets/131114036/a1ecb2cc-6f0a-490b-a884-fe0edc44064d)
![frame_1468](https://github.com/harisreedhar/Swap-Mukham/assets/131114036/6762f051-010c-45fe-b364-e0881b888727)
![frame_2212](https://github.com/harisreedhar/Swap-Mukham/assets/131114036/8c9af942-cdc4-4c57-b9e2-fd70c27cbe7a)
![frame_2344](https://github.com/harisreedhar/Swap-Mukham/assets/131114036/9a527ecd-3815-41f7-8dde-32aa77618cad)

**Comment by mukeshsnp12** [comment]
![1b037042965145 57deca8a92d2b](https://github.com/harisreedhar/Swap-Mukham/assets/131114036/ff106366-48bd-429f-a9f7-2448f4d05a24)

**Comment by harisreedhar** [comment]
Show some dignity bro. This repo is not for creating NSFW contents !!!

**Comment by mukeshsnp12** [comment]
Sorry for these. I was trying capture every expression and face movement. These are not NSFW, I deleted these too. But hope you got my point.

**Comment by harisreedhar** [comment]
May be reducing ``detection threshold`` from ``0.5`` to ``0.2`` or lower will help to detect face.
