### ISSUE TITLE
Loss of video bitrate/quality

### ISSUE THREAD

**Issue by recycleaway7** [harisreedhar/Swap-Mukham#26]
For video processing I'm getting inconsistent video bitrate results and I'm not sure why. Sometimes it seems to lose about half of the video bitrate and sometimes it drops even more than that. The length of the video might be a factor but I'm still testing. Most of my source videos have a video bitrate around 20000kbps but the final results are usually in the 2000kbps to 10000kbps range. What variables are going to influence that for the results? Is there anything that I can do to preserve the video bitrate from the original source video?

**Comment by harisreedhar** [comment]
Through UI it is not implemented yet, I will add more user adjustable output settings in the future.

For now you can set output bitrate by modifying this line of code:
https://github.com/harisreedhar/Swap-Mukham/blob/7d3ed05c0756003d7dc9c296938baa7d04538274/utils.py#L137
to this:
``output_file_name, codec="libx264", bitrate="20000k"``

similarly for trimmed videos:
https://github.com/harisreedhar/Swap-Mukham/blob/7d3ed05c0756003d7dc9c296938baa7d04538274/utils.py#L29
to this:
``trimmed_video_file_path, codec="libx264", audio_codec="aac", bitrate="20000k"``

**Comment by harisreedhar** [comment]
I have added automatic bitrate for each resolution. (not the best implementaion i will improve it later)
