### ISSUE TITLE
Use CodeFormer for Face Enhancer

### ISSUE THREAD

**Issue by SamPse** [harisreedhar/Swap-Mukham#28]
Is it possible to use CodeFormer for Face Enhancer?

**Comment by harisreedhar** [comment]
@SamPse It is planned. Now i'm working on fixing bugs and optimising the code for better performance. Codeformer will be added after that.

**Comment by SamPse** [comment]
> @SamPse It is planned. Now i'm working on fixing bugs and optimising the code for better performance. Codeformer will be added after that.


You did a very good job congratulations ‎👏

**Comment by SamPse** [comment]
I have another question the mask at the level of the beard is a little short and it is possible to lower it ?

**Comment by harisreedhar** [comment]
@SamPse Not possible

**Comment by SamPse** [comment]
> @SamPse Not possible

Thank you for the answer the Face Scale parameter solves this problem !
