### ISSUE TITLE
Please document best versions of Cuda and Cudnn to install for windows (and maybe other OS)

### ISSUE THREAD

**Issue by robertdbruce** [harisreedhar/Swap-Mukham#3]
Hi !

I have an Nvidia 2080 Ti and Windows 11 - was running Cuda 12 but apparently that's too new ?

Currently your requirements.txt seems to point to onnxruntime v 1.15.0

https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html gives some more detail here but 1.14 is the latest version on that page.

So I wondered - should I run CUDA 11.6 and CuDNN 8.5.0.96 if I'm on Windows? is that enough for onnx 1.15 ?

https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html isn't super clear (as above)
https://developer.nvidia.com/rdp/cudnn-archive  is also pretty unclear but it turns out 8.5.0 is actually 8.5.0.96

I eventually settled on Cuda 11.6 and CuDNN 8.5 and tried it,

initially I had the following error:
"Could not locate zlibwapi.dll. Please make sure it is in your library path!"

I just needed to follow this:
https://docs.nvidia.com/deeplearning/cudnn/install-guide/index.html#prerequisites-windows

now it works perfectly !

It's just not clear what versions of everything are required so if you could document this it would help newbies like me a lot.

Cheers !

**Comment by harisreedhar** [comment]
Adding gpu support is planned. Current code is cpu only. I should remove ``onnxruntime`` from ``requirements.txt`` since it is not using it.

**Comment by robertdbruce** [comment]
Ah yes, I completely forgot I swapped out the comments on lines 24 and 25 of app.py, which *I thought* had brought GPU support to life:

2023-06-21 20:39:59.1959450 [W:onnxruntime:, graph.cc:3543 onnxruntime::Graph::CleanUnusedInitializersAndNodeArgs] Removing initializer 'buff2fs'. It is not used by any node and should be removed from the model.
Applied providers: ['CUDAExecutionProvider', 'CPUExecutionProvider'], with options: {'CUDAExecutionProvider': {'do_copy_in_default_stream': '1', 'cudnn_conv_algo_search': 'EXHAUSTIVE', 'device_id': '0', 'gpu_external_alloc': '0', 'enable_cu

But looking at the code again, other than checking available execution providers, it doesn't seem to reference the onnxruntime again, so you're right of course.

But it's still very fast (faster than roop in CPU mode for example) so kudos !
