### ISSUE TITLE
How can I change the port?

### ISSUE THREAD

**Issue by visualhippocracy** [harisreedhar/Swap-Mukham#31]
Hi,

Is there a way to change the port being used to something other than 7860, im using SD on 7860 and would like to keep it on that port only, difficult running this and SD at the same time

**Comment by harisreedhar** [comment]
Modify this line of code in ``app.py``

``interface.queue(concurrency_count=2, max_size=20).launch(share=USE_COLAB)``

to

``    interface.queue(concurrency_count=2, max_size=20).launch(share=USE_COLAB, port=7861)``
