### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by XTRMsavage** [harisreedhar/Swap-Mukham#33]
I have installed anaconda and followed the instructions, but when I do the last step of code in the cmd prompt I get this message "(swapmukham) D:\Swap-Mukham\Swap-Mukham>python app.py --cuda --batch_size 32
Traceback (most recent call last):
  File "D:\Swap-Mukham\Swap-Mukham\app.py", line 2, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'

(swapmukham) D:\Swap-Mukham\Swap-Mukham>"

None of the python files open (app, face_analyser, face_enhancer, face_swapper, etc). 

what's the reason?

**Comment by harisreedhar** [comment]
It means you haven't installed opencv. Make sure that all packages inside ``requirements.txt`` is installed.

**Comment by XTRMsavage** [comment]
ok, I installed in C drive and it's working. Thanks
