### ISSUE TITLE
Run On Google Colab Support

### ISSUE THREAD

**Issue by ashegh8** [harisreedhar/Swap-Mukham#4]
Is it possible to run this source on Google Colab?

**Comment by harisreedhar** [comment]
could be possible but not on my priority

**Comment by shanmugad** [comment]
@ashegh8 @harisreedhar Do you have notebook code?

**Comment by harisreedhar** [comment]
@shanmugad No.

**Comment by harisreedhar** [comment]
@ashegh8 @shanmugad Added [colab notebook](https://colab.research.google.com/github/harisreedhar/Swap-Mukham/blob/main/swap_mukham_colab.ipynb)
