### ISSUE TITLE
Acceleration in Mac M1

### ISSUE THREAD

**Issue by SamPse** [harisreedhar/Swap-Mukham#47]
Any plan to use onnxruntime-silicon?
pip install onnxruntime-silicon==1.13.1

python run.py --execution-provider coreml

**Comment by harisreedhar** [comment]
Only cuda and cpu support will be officially supported. But the next update i'm working on will replace all models to ``onnx``. So users can easily modify ``execution providers`` from ``cuda`` to ``coreml``.

**Comment by SamPse** [comment]
> Only cuda and cpu support will be officially supported. But the next update i'm working on will replace all models to `onnx`. So users can easily modify `execution providers` from `cuda` to `coreml`.

Good news and congratulations again for your work :)
