### ISSUE TITLE
Directory mode giving error

### ISSUE THREAD

**Issue by wogam** [harisreedhar/Swap-Mukham#48]
When using 'Directory', it throws an error. The directory only has video files. When selecting the video files individually, and selecting 'video' it works fine. 

> IndexError: list index out of range
> Analysing face data: 0it [00:00, ?it/s]
> Generating face: 0it [00:00, ?it/s]
> Upscaling with CodeFormer: 0it [00:00, ?it/s]
> Pasting back: 0it [00:00, ?it/s]
> Traceback (most recent call last):
>   File "D:\.conda\envs\swapmukham\lib\site-packages\gradio\routes.py", line 442, in run_predict
>     output = await app.get_blocks().process_api(
>   File "D:\.conda\envs\swapmukham\lib\site-packages\gradio\blocks.py", line 1392, in process_api
>     result = await self.call_function(
>   File "D:\.conda\envs\swapmukham\lib\site-packages\gradio\blocks.py", line 1111, in call_function
>     prediction = await utils.async_iteration(iterator)
>   File "D:\.conda\envs\swapmukham\lib\site-packages\gradio\utils.py", line 346, in async_iteration
>     return await iterator.__anext__()
>   File "D:\.conda\envs\swapmukham\lib\site-packages\gradio\utils.py", line 339, in __anext__
>     return await anyio.to_thread.run_sync(
>   File "D:\.conda\envs\swapmukham\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
>     return await get_asynclib().run_sync_in_worker_thread(
>   File "D:\.conda\envs\swapmukham\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
>     return await future
>   File "D:\.conda\envs\swapmukham\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
>     result = context.run(func, *args)
>   File "D:\.conda\envs\swapmukham\lib\site-packages\gradio\utils.py", line 322, in run_sync_iterator_async
>     return next(iterator)
>   File "D:\.conda\envs\swapmukham\lib\site-packages\gradio\utils.py", line 691, in gen_wrapper
>     yield from f(*args, **kwargs)
>   File "D:\Swap-Mukham\app.py", line 421, in process
>     PREVIEW = cv2.imread(file_paths[-1])[:, :, ::-1]
> IndexError: list index out of range
> Analysing face data: 0it [00:00, ?it/s]
> Generating face: 0it [00:00, ?it/s]
> Upscaling with CodeFormer: 0it [00:00, ?it/s]
> Pasting back: 0it [00:00, ?it/s]
> Traceback (most recent call last):
>   File "D:\.conda\envs\swapmukham\lib\site-packages\moviepy\video\io\ffmpeg_reader.py", line 285, in ffmpeg_parse_infos
>     line = [l for l in lines if keyword in l][index]
> IndexError: list index out of range

**Comment by harisreedhar** [comment]
Directory only support images

**Comment by wogam** [comment]
Is there anyway to support multiple videos or to queue multiple tasks?

**Comment by harisreedhar** [comment]
@wogam Not possible atm.
