### ISSUE TITLE
IS GFPGAN better than CodeFormer？

### ISSUE THREAD

**Issue by KittenYang** [harisreedhar/Swap-Mukham#50]
CodeFormer：https://huggingface.co/spaces/sczhou/CodeFormer

why not use CodeFormer instead of GFPGAN？

**Comment by harisreedhar** [comment]
Codeformer is already there you just have to download [codeformer.onnx](https://github.com/harisreedhar/Face-Upscalers-ONNX/releases/download/Models/codeformer.onnx) and put it inside ``assets/pretrained_models``.
