### ISSUE TITLE
Choose which face or faces in the target image to swap.

### ISSUE THREAD

**Issue by senthil2k9** [harisreedhar/Swap-Mukham#58]
Only all face is working, all other specific faces not working

**Comment by harisreedhar** [comment]
@senthil2k9 In older version or new wip?

**Comment by mukeshsnp12** [comment]
@harisreedhar  How to choose face in new wip?

**Comment by harisreedhar** [comment]
> @harisreedhar  How to choose face in new wip?

Same as older version

**Comment by senthil2k9** [comment]
I am using new wip.. Old one working fine. Ex all Male or all Female is not working in new wip.

**Comment by harisreedhar** [comment]
@senthil2k9 Are you sure using latest version? Because yesterday i changed gender_age model. [model link](https://github.com/harisreedhar/Swap-Mukham/tree/new-wip#download-and-place-these-models-under-assetspretrained_models)

**Comment by senthil2k9** [comment]
I pulled latest code, Now its working thanks
