### ISSUE TITLE
How to increase face likeliness?

### ISSUE THREAD

**Issue by LLSean** [harisreedhar/Swap-Mukham#60]
Do you have an idea? How to increase face similarity and use iteration to easily increase contrast in images

**Comment by harisreedhar** [comment]
In [WIP branch](https://github.com/harisreedhar/Swap-Mukham/tree/new-wip) there is new feature called ``Swap Iteration`` which may increase face likeliness.

**Comment by LLSean** [comment]
I tried the Swap Iteration feature and it will increase contrast in images.

**Comment by harisreedhar** [comment]
just use iteration of 2. More than that usually doesn't look that good.

**Comment by LLSean** [comment]
Thanks a lot.
