### ISSUE TITLE
No GPU usage (Google Colab)

### ISSUE THREAD

**Issue by shanmugad** [harisreedhar/Swap-Mukham#7]
Hello, 

First, i want to thank you adding Google Colab notebook. 

I noticed, current notebook only use CPU even the runtime resource have GPU.  While testing, i saw GPU usage remained at 0. 

Screenshot attached!

![image](https://github.com/harisreedhar/Swap-Mukham/assets/121617479/4a257482-fa3d-491e-8b00-6f224569bb37)

**Comment by harisreedhar** [comment]
@shanmugad It was due to onnxruntime-gpu version. I fixed it.
Can you check again?

**Comment by shanmugad** [comment]
![image](https://github.com/harisreedhar/Swap-Mukham/assets/121617479/e14efd55-01b3-45a9-912f-524ef7b7e100)

Fixed
