### ISSUE TITLE
Add optional LDSR pre-stage

### ISSUE THREAD

**Issue by xnrfn** [harisreedhar/Swap-Mukham#78]
Over at https://github.com/glucauze/sd-webui-faceswaplab/blob/main/scripts/faceswaplab_swapping/upscaled_inswapper.py LDSR is used at a pre-stage to upscale the output from inswapper. This produces hugely better results, at the expense of more processing time.

It's so much better that actually GFPGAN could be preferable over CodeFormers in post, but that's in the eye of the beholder.

Could you add this as an option?

**Comment by harisreedhar** [comment]
We can add preupscale option but LDSR integration requires lot of work, since swap-mukham is an independent project we cannot pull modules from automatic1111 like faceswaplab.

**Comment by xnrfn** [comment]
LDSR is standalone and predates stable diffusion: https://github.com/CompVis/latent-diffusion 

Does not look overly complicated if you look at scripts/ in that repo? I'm just pointing to faceswaplab as an example implementation.

**Comment by xnrfn** [comment]
So I've done some searching to find an easily accessible implementation, and https://huggingface.co/spaces/Iceclear/StableSR is hugely impressive. If you take an original high-res photo, take it down to 128x128, then use StableSR to take it back to an 8x upscale on either 512 of 768v, it's impressive how accurate it is. Downside is that it is extremely slow, but even a 2x or 3x would already be massively beneficial and that might be fast enough.

**Comment by xnrfn** [comment]
drop this, found a much faster option. will open new issue
