### ISSUE TITLE
Can you create a bat file to run package without opening conda?

### ISSUE THREAD

**Issue by mukeshsnp12** [harisreedhar/Swap-Mukham#9]
I am not experienced programmer. Can you create a bat file to run package without opening conda prompt every time to run program?

**Comment by harisreedhar** [comment]
I'm not on windows. But simple chatgpt query made me this:
````bat
@echo off
conda activate swapmukham
python path/to/your/app.py
````
save it as run.bat

**Comment by mukeshsnp12** [comment]
Thanks, It didn't work, but I created bat file.

**Comment by mukeshsnp12** [comment]
@echo off
call conda activate swapmukham
python "app.py"

**Comment by mukeshsnp12** [comment]
add a batch file in program so, it is easy for windows user
